# Introduction to NumPy

In [17]:
import numpy as np
import random
import timeit

## Why NumPy?

In [18]:
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

In [19]:
%%timeit
multiplication = [a*b for a,b in zip(list1,list2)]

150 ms ± 26.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
list1 = np.array(list1)
list2 = np.array(list2)

In [21]:
%%timeit
multiplication = np.multiply(list1,list2)

11 ms ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%%timeit
multiplication = list1 * list2

6.55 ms ± 857 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# np.array

In [23]:
list1 = [12, 28, 7, 34, 45, 6, 50, 16, 18, 19]

In [24]:
len(list1)

10

In [25]:
array = np.array(list1)
array

array([12, 28,  7, 34, 45,  6, 50, 16, 18, 19])

In [11]:
array.shape

(10,)

In [26]:
array.size

10

In [27]:
type(array)

numpy.ndarray

In [28]:
array[0]

np.int64(12)

In [29]:
array[2]

np.int64(7)

In [30]:
array[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [31]:
mat = np.array(
    [
		[1,2],
		[3,4],
		[5,6]
	]
)

In [32]:
mat.shape

(3, 2)

In [33]:
mat[0, 1]

np.int64(2)

In [34]:
mat[:, 1]

array([2, 4, 6])

In [35]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
mat[:1, 1]

array([2])

In [37]:
mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
mat.shape

(3, 2)

In [39]:
mat.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
mat.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
zeroes = np.zeros((3, 4, 10))
zeroes

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [49]:
zeroes.size

120

In [53]:
zeroes.reshape((3, 40))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
mat.flatten()

array([1, 2, 3, 4, 5, 6])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.arange()

In [44]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [45]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

np.linspace()

In [46]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [47]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [55]:
np.int8, np.int16, np.int32, np.int64

(numpy.int8, numpy.int16, numpy.int32, numpy.int64)

In [56]:
np.float16, np.float32, np.float64

(numpy.float16, numpy.float32, numpy.float64)

In [57]:
np.double

numpy.float64

In [59]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [60]:
array[array > 5]

array([ 6,  7,  8,  9, 10])