# Introduction to NumPy

In [26]:
import numpy as np
import random
import timeit

## Why NumPy?

In [20]:
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

In [21]:
%%timeit
multiplication = [a*b for a,b in zip(list1,list2)]

226 ms ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
list1 = np.array(list1)
list2 = np.array(list2)

In [27]:
%%timeit
multiplication = np.multiply(list1,list2)

9.6 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%timeit
multiplication = list1 * list2

6.98 ms ± 507 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# np.array

In [30]:
list1 = [12, 28, 7, 34, 45, 6, 50, 16, 18, 19]

In [32]:
len(list1)

10

In [33]:
array = np.array(list1)
array

array([12, 28,  7, 34, 45,  6, 50, 16, 18, 19])

In [34]:
array.shape

(10,)

In [39]:
array.size

10

In [40]:
type(array)

numpy.ndarray

In [65]:
array[0]

np.int64(12)

In [66]:
array[2]

np.int64(7)

In [112]:
array[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [100]:
mat = np.array(
    [
		[1,2],
		[3,4],
		[5,6]
	]
)

In [101]:
mat.shape

(3, 2)

In [102]:
mat[0, 1]

np.int64(2)

In [103]:
mat[:, 1]

array([2, 4, 6])

In [104]:
mat[:1, 1]

array([2])

In [105]:
mat.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
mat.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [107]:
mat.flatten()

array([1, 2, 3, 4, 5, 6])

In [41]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.arange()

In [51]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [49]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

np.linspace()

In [57]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [58]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])